## Numpy

In [1]:
# 一維陣列
import numpy as np
x = np.array([1,2,3])
print(x)
print(x[0])
x[1] = 3
print(x)

[1 2 3]
1
[1 3 3]


In [2]:
import numpy as np
x = np.array([1,2,3])
print(x.ndim)
print(x.shape) # 元素個數的元祖
print(x.size) # 元素個數

1
(3,)
3


In [3]:
import numpy as np
x = np.arange(1,6) # 建立陣列
print(x)
y = np.zeros(5, dtype=np.int_) # dtype 預設式浮點數陣列
print(y)
z = np.ones(5)
print(z)

[1 2 3 4 5]
[0 0 0 0 0]
[1. 1. 1. 1. 1.]


In [4]:
import numpy as np
x = np.array([1,2,3,4,5,6,7,8])
# 切片
print(x[0:3])
print(x[-1])
print('-----------------')
# 陣列結合 或 加入陣列元素
y = np.array([4,5])
z = np.concatenate((x,y))
print(z)
print('-----------------')
# 在陣列指定索引插入元素
z1 = np.insert(x,2,9) # 指定索引2插入元素9
print(z1)
print('-----------------')
# 刪除指定索引的陣列元素
z2 = np.delete(x,[1,3]) # 刪除索引1和3
print((z2))

[1 2 3]
8
-----------------
[1 2 3 4 5 6 7 8 4 5]
-----------------
[1 2 9 3 4 5 6 7 8]
-----------------
[1 3 5 6 7 8]


In [6]:
# 二維陣列
import numpy as np
x = np.array([[1,2,3],[4,5,6]])
print(x)
print(x.ndim)
print(x.shape)
print(x.size)

[[1 2 3]
 [4 5 6]]
2
(2, 3)
6


In [7]:
import numpy as np
x = np.array([[1,2,3],[4,5,6]])
y = np.array([[7,8,9],[10,11,12]])
z = x > y
print(z)

[[False False False]
 [False False False]]


In [8]:
import numpy as np
x = np.array([[1,2,3],[4,5,6]])
x[1,2] = 10
print(x)
# 切片
print(x[0:2,0:2]) # row, column

[[ 1  2  3]
 [ 4  5 10]]
[[1 2]
 [4 5]]


In [10]:
import numpy as np
x = np.array([[1,2,3],[4,5,6]])
y = x.ravel() # 轉成一維陣列
print(y)
print('----------')
x1 = np.array([1,2,3,4,5,6])
y1 = x1.reshape(2,3)
print(y1)
print('-------------')
# 矩陣轉置
y2 = y1.transpose()
print(y2)

[1 2 3 4 5 6]
----------
[[1 2 3]
 [4 5 6]]
-------------
[[1 4]
 [2 5]
 [3 6]]


In [14]:
import numpy as np
# 矩陣堆疊
x = np.arange(6).reshape(2,3)
y = np.arange(1,7).reshape(2,3)
print(x)
print(y)

z1 = np.vstack((x,y)) # 垂直方向堆疊
z2 = np.column_stack((x,y))
z3 = np.row_stack((x,y))
print(z1)
print(z2)
print(z3)

[[0 1 2]
 [3 4 5]]
[[1 2 3]
 [4 5 6]]
[[0 1 2]
 [3 4 5]
 [1 2 3]
 [4 5 6]]
[[0 1 2 1 2 3]
 [3 4 5 4 5 6]]
[[0 1 2]
 [3 4 5]
 [1 2 3]
 [4 5 6]]


## Pandas

In [16]:
# Series是一種一維陣列資料結構
import pandas as pd
s1 = pd.Series([1,2,3,4,5])
s1
s1[1] = 3
s1

0    1
1    3
2    3
3    4
4    5
dtype: int64

In [17]:
import pandas as pd
s2 = pd.Series({'台灣':'Taiwan','東京':'Tokyo'})
s2

台灣    Taiwan
東京     Tokyo
dtype: object

In [19]:
import pandas as pd
import numpy as np
s3 = pd.Series(np.arange(0,7,2))
s3

0    0
1    2
2    4
3    6
dtype: int32

In [21]:
import pandas as pd
myindex = [3,4,5] # 自訂索引
price = [100,200,300]
s4 = pd.Series(price, index=myindex)
s4

3    100
4    200
5    300
dtype: int64

In [22]:
# 切片
import pandas as pd
s = pd.Series([0,1,2,3,4,5])
s[2:5]

2    2
3    3
4    4
dtype: int64

In [23]:
# 四則運算
import pandas as pd
x = pd.Series([1,2])
y = pd.Series([3,4])
z = x + y
z

0    4
1    6
dtype: int64

In [26]:
# 使用Series物件成為二維陣列
import pandas as pd
years = range(2020, 2023)
country1 = pd.Series([18,19,20], index=years)
country2 = pd.Series([25,26,27], index=years)
citydf = pd.concat([country1,country2], axis=0)
print(citydf)

2020    18
2021    19
2022    20
2020    25
2021    26
2022    27
dtype: int64


In [27]:
import pandas as pd
years = range(2020, 2023)
country1 = pd.Series([18,19,20], index=years)
country2 = pd.Series([25,26,27], index=years)
citydf = pd.concat([country1,country2], axis=1)
print(citydf)

       0   1
2020  18  25
2021  19  26
2022  20  27


In [28]:
import pandas as pd
years = range(2020, 2023)
country1 = pd.Series([18,19,20], index=years)
country2 = pd.Series([25,26,27], index=years)
citydf = pd.concat([country1,country2], axis=1)
city = ['Taipei','Tokyo']
citydf.columns = city
print(citydf)

      Taipei  Tokyo
2020      18     25
2021      19     26
2022      20     27


In [36]:
# DataFrame 是一個二維的陣列資料結構
import pandas as pd
data1 = [{'apple':50, 'orange':40},{'apple':45, 'orange':50}]
df1 = pd.DataFrame(data1)
print(df1)

   apple  orange
0     50      40
1     45      50


In [42]:
import pandas as pd
data2 = {'apple':[50,45], 
          'orange':[45,50]}
fruitindex = ['1','2']
df2 = pd.DataFrame(data2, index = fruitindex)
print(df2)

   apple  orange
1     50      45
2     45      50


In [45]:
# Pnadas 資料處理與分析
import pandas as pd
cities = {'country':['China','Japan','Taiwan'],
          'town':['Beijing','Tokyo','Taipei'],
          'population':[2000,1600,230]}
cityindex = ['first','second','third']
citydf = pd.DataFrame(cities, index=cityindex)
citydf

country     town  population
first    China  Beijing        2000
second   Japan    Tokyo        1600
third   Taiwan   Taipei         230

In [46]:
# 索引參照屬性
print(citydf.at['first','town']) # row, column

Beijing


In [47]:
print(citydf.iat[0,1]) 

Beijing


In [49]:
print(citydf.loc['first']) 

country         China
town          Beijing
population       2000
Name: first, dtype: object


In [48]:
print(citydf.iloc[0]) 

country         China
town          Beijing
population       2000
Name: first, dtype: object


In [50]:
print(citydf[citydf['population'] > 1000]) 

       country     town  population
first    China  Beijing        2000
second   Japan    Tokyo        1600
